### PR TITLE
Fetch related works when document is loaded

### LINKED ISSUE #3818: Rm cache option for Related Books Carousel & fix js trigger
Related Books carousels spin forever. The function call itself may be consistently failing and then caching an empty value. Or we are not reponding to errors correctly.

### Evidence / Screenshot (if possible)
See spinner on live website on books page, e.g. ...

### Relevant url?

https://openlibrary.org/books/OL7829676M/The_Giver

### Steps to Reproduce

1. Go to ...
2. Do ...

Hit the endpoint directly or go to works or books page
https://openlibrary.org/partials?workid=OL1934404W&_components=RelatedWorkCarousel

* Actual: 
* Expected: 

### Related files

plugins/openlibrary/code.py

### PR DESCRIPTION
**Pull request by jamesachamp**
Closes #3818

This PR ensures that the AJAX call for the related works carousels only occurs when the document has fully loaded.  Thanks to @shaneriley for identifying the issue, here: https://github.com/internetarchive/openlibrary/issues/3818#issuecomment-712361206

### Technical

If `document.readyState === 'complete'` when the carousel partials are initialized, the related works AJAX call is made.  Otherwise, the AJAX call is attached as a callback to `window.onload`.
### Testing

I was able to test both cases locally in Chrome.
Navigating directly to a book page typically caused the code inside of the `document.readyState === 'complete'` if block to execute. Navigating away from that page and pressing Chrome's back button typically caused the code in the `else` block to execute.

### CODE REVIEW

**Review by mekarpeles — APPROVED** [review]

**Comment by perryjr** [comment]
I just noticed an issue in prod where related books carousel doesn't load after using the back button. It seems to 'spin' indefinitely.  I only have the sample data in my local db which made it difficult to test locally whether this commit resolved the issue or not.  I thought I would ask whether  this commit was intended to fix that issue before I report/fix something that's already resolved.

**Comment by jamesachamp** [comment]
This should correct that issue.  Are you able to reproduce this in [dev](https://dev.openlibrary.org)?  I don't think that this code is currently in production.

Regardless of this code change, the loading indicator can also be displayed indefinitely if the related works AJAX call fails.  The indicator is only hidden on success.

**Comment by perryjr** [comment]
Sorry for the delay on this - hoping to check tonight thought it does seem like hiding the element after a failed ajax call will resolve everything except why the ajax might fail.  I don't yet know whether it's actually failing or not but I'll check it out. AND I missed today's meeting :(

File: openlibrary/plugins/openlibrary/js/carousels_partials.js [hunk 1]
```diff
@@ -29,5 +29,13 @@ export function initCarouselsPartials() {
                 }
             }
         });
-    });
+    };
+
+    $('.loadingIndicator').removeClass('hidden');
+
+    if (document.readyState === 'complete') {
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/carousels_partials.js:36]: This should always be true at this point, from my understanding of the code.

File: openlibrary/plugins/openlibrary/js/carousels_partials.js [hunk 2]
```diff
@@ -29,5 +29,13 @@ export function initCarouselsPartials() {
...
+        fetchRelatedWorks();
+    } else {
+        $(window).on('load', fetchRelatedWorks);
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/carousels_partials.js:39]: I'm not sure about this code - it's already inside a jQuery ready event in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/index.js#L114 

I think the issue here is that we are registering a window.load event /way after/ the load event has occurred.

My first thought it that calling `fetchRelatedWorks();` outside a window.load event should have exactly the same effect.

Comment (jamesachamp) [reply openlibrary/plugins/openlibrary/js/carousels_partials.js:39]: > I think the issue here is that we are registering a window.load event /way after/ the load event has occurred.

I think that you are right about this.  Do you think that it would be better to remove the conditional and simply call `fetchRelatedWorks()`?

Comment (jdlrobson) [reply openlibrary/plugins/openlibrary/js/carousels_partials.js:39]: I think so.
If that doesn't work it would indicate a more serious problem with how we load our code that I'd like to look into.

File: openlibrary/plugins/openlibrary/js/carousels_partials.js (hunk 1 above)
Comment (jamesachamp) [reply openlibrary/plugins/openlibrary/js/carousels_partials.js:36]: I was able to enter the `else` block by navigating to a book page using the browser's back button.

Comment (jdlrobson) [reply openlibrary/plugins/openlibrary/js/carousels_partials.js:36]: Sorry meant falsey

Complete: The document and all sub-resources have finished loading. The state indicates that the load event is about to fire.

Else would mean the document (styles, scripts)is still loading or interactive.

I think the only case where this would be true on second thoughts is when this gets lazy loaded last.

Either way I don't think it should matter 
https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState

I do vaguely remember some issues with back button/cached pages and window.onload and older jquery versions so that's possibly what we are hitting here.

Drop the window.load event. Should not be needed
