### PR TITLE
#1395 Add no-unused-vars and fix all errors

### LINKED ISSUE #1397: Eslint fix no-unused-vars
We have eslint linting for our JS. Let's add a rule for [no-unused-vars](https://eslint.org/docs/rules/) as this will remove a lot of dead code. There are 67 errors in the existing codebase that need to be fixed manually. Let's get those fixed.
```
    "no-unused-vars": "error",
```

- [ ] Add the rule no-unused-vars to .eslintrc.json
- [ ] Fix all offenders

Note: some offenders may be exposed by globals and needed by templates. If that's the case make sure the variable is marked with a eslint-disable-next-line comment

### PR DESCRIPTION
**Pull request by Atul9**
Closes #1397 

## Description:
In this Pull Request we have made the following changes:
1. Add the rule no-unused-vars to .eslintrc.json
2. Fix all offenders

### CODE REVIEW

**Comment by jdlrobson** [comment]
Are any of these unused variables used inside templates (directly in the html)?

I suspect for many of them this will be true. Can you grep the templates folder to check?

**Comment by Atul9** [comment]
@jdlrobson @mekarpeles I ran grep command on templates directory and removed unused vars. I have updated the PR.

**Comment by jdlrobson** [comment]
The ones that we don't remove we will need to wrap in a disable block, ideally pointing to where it is used! Otherwise this change won't pass CI
E.g.

```
/* eslint-disable no-unused-vars */
// used in template/foo.html

Unusedvar ={}
/* eslint-enable no-unused-vars */

**Comment by Atul9** [comment]
@jdlrobson done. I have updated the PR.

File: openlibrary/plugins/openlibrary/js/ol.js [hunk 1]
```diff
@@ -708,7 +541,6 @@ $().ready(function(){
         } else {
             dropdown.slideToggle(25);
             $(this).toggleClass('hover');
-            var offUser = $(this);
             $(document).mouseup(function(offUser){
```
[the remark this answers is not in the document]
Comment (jdlrobson) [reply openlibrary/plugins/openlibrary/js/ol.js]: This reference is likely broken. mouseup is passed an "ev" and can't be used this way.

This  fix is correct but has likely uncovered a bug.

**Comment by jdlrobson** [comment]
@Atul9 I want to take a thorough look at this one so apologies in advance if I take time reviewing this on. Thank you for working on it!

File: openlibrary/plugins/openlibrary/js/account.js [hunk 2]
```diff
@@ -1,54 +1,3 @@
-function setup_account_create() {
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/account.js]: nice catch! I am not seeing any usages either.

File: openlibrary/plugins/openlibrary/js/add_new_field.js [hunk 3]
```diff
@@ -14,7 +14,7 @@
  *     - On cancel/close:
  *         - value of the select is set to "" to select "select xxx"
  */
-;(function($){
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/add_new_field.js]: probably don't want to fix these just yet.. 
we are blindly concatenating JS so removing this could throw errors (hence why it's warning and not erroring right now)

Imagine what happens if you concatenate

```
setTimeout()
```
with 
```
(function(){})
```
😨

File: openlibrary/plugins/openlibrary/js/autocomplete.js [hunk 4]
```diff
@@ -1,6 +1,6 @@
 // jquery plugins to provide author and language autocompletes.
 
-;(function($) {
+(function($) {
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/autocomplete.js]: see comment above

File: openlibrary/plugins/openlibrary/js/subjects.js [hunk 5]
```diff
@@ -12,9 +12,9 @@
 //          });
 //
 
-;(function() {
+(function() {
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/subjects.js]: see comments above

File: openlibrary/plugins/openlibrary/js/utils.js [hunk 6]
```diff
@@ -1,4 +1,4 @@
-;(function($) {
+(function($) {
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/utils.js]: (Above)

File: openlibrary/plugins/openlibrary/js/add_new_field.js (hunk 3 above)
Comment (Atul9) [reply openlibrary/plugins/openlibrary/js/add_new_field.js]: okay, I have added `;` back and updated the PR.

File: openlibrary/plugins/openlibrary/js/autocomplete.js (hunk 4 above)
Comment (Atul9) [reply openlibrary/plugins/openlibrary/js/autocomplete.js]: okay, I have added `;` back and updated the PR.

File: openlibrary/plugins/openlibrary/js/subjects.js (hunk 5 above)
Comment (Atul9) [reply openlibrary/plugins/openlibrary/js/subjects.js]: okay, I have added `;` back and updated the PR.

File: openlibrary/plugins/openlibrary/js/utils.js (hunk 6 above)
Comment (Atul9) [reply openlibrary/plugins/openlibrary/js/utils.js]: okay, I have added `;` back and updated the PR.

File: openlibrary/plugins/openlibrary/js/ol.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (hornc) [reply openlibrary/plugins/openlibrary/js/ol.js]: @jdlrobson @mekarpeles is this safe to merge at this stage? I'm unsure of status / next steps for this one `offUser`?

[the remark this answers is not in the document]
Comment (jdlrobson) [reply openlibrary/plugins/openlibrary/js/ol.js]: This can safely be removed.

The line below should probably be rewritten like so:
```
$(document).mouseup(function(ev){
if($(ev.target).parent("a").length==0){
```

but that can be done in a follow up.
