### PR TITLE
Fixed Read More Button Display Logic to Avoid Unnecessary Display

### LINKED ISSUE #9329: "Read more" button should not be added if it takes up as much space as the hidden text
#### Evidence / Screenshot

image
image

#### Relevant URL(s)

E.g. https://openlibrary.org/books/OL8978501M/Robin_Hood

### Reproducing the bug

1. Go to https://openlibrary.org/books/OL8978501M/Robin_Hood

* Expected behavior: Description not collapsed, since "read more" makes the section actually longer :P
* Actual behavior: "Read more" shown over description

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Win
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Proposal & constraints
Perhaps we can update the `+ 1` here: https://github.com/internetarchive/openlibrary/blob/73b70f6b997c401caf2fe8078a6296c8f3167ee5/openlibrary/plugins/openlibrary/js/readmore.js#L58

To instead be the height of the `.read-more__toggle--more` button. We might need to capture that height in the constructor though, before the read more button is potentially hidden!

#### Related files
https://github.com/internetarchive/openlibrary/blob/73b70f6b997c401caf2fe8078a6296c8f3167ee5/openlibrary/plugins/openlibrary/js/readmore.js

#### Stakeholders
@RayBB 

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

### PR DESCRIPTION
**Pull request by CodeMaverick2**
---
## Description

This PR addresses an issue where the "Read more" button was displayed even when it extended the section beyond its fully expanded content. This led to a confusing user experience, as the "Read more" button was not serving its intended purpose. The following changes have been made to resolve this issue:

**Closes #9329**

## Changes

1. **Capture "Read More" Button Height**:
    - The height of the "Read more" button is now captured during initialization to ensure accurate layout calculations.

2. **Updated Condition in `reset` Method**:
    - The logic determining whether the "Read more" button should be displayed has been updated to account for the button's height. This ensures the button is only shown when necessary.

## Impact

- **Improved User Experience**: The "Read more" button is now displayed only when needed, reducing unnecessary clutter and confusion.
- **Correct Layout Behavior**: The layout now behaves as expected, with the "Read more" button enhancing usability instead of detracting from it.

## Testing
To test visit a link like https://testing.openlibrary.org/books/OL8978501M/Robin_Hood
---

## Screenshots
Screenshot from 2024-07-25 18-43-42

### CODE REVIEW

**Comment by RayBB** [comment]
@CodeMaverick2 please do not keep opening new PRs for the same issue. When feedback is given address it in that PR.
That being said, have you addressed all of @cdrini 's feedback in https://github.com/internetarchive/openlibrary/pull/9871 ?

Please note that the team is still working on getting Open Library Fully operational so may not be able to review this soon.

**Comment by RayBB** [comment]
@CodeMaverick2 have you addressed all of cdrini 's feedback in #9871 ?

**Comment by CodeMaverick2** [comment]
Yes

**Review by RayBB — APPROVED** [review]
Great job! Tested locally and it seems to be working well.

Now we need @cdrini to review/merge.

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 1]
```diff
@@ -52,10 +52,13 @@ export class ReadMoreComponent {
     }
 
     reset() {
-        this.fullHeight = this.$content.scrollHeight;
+        const fullHeight = this.$content.scrollHeight;
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/readmore.js:55]: This should still be `this.fullHeight`; the `reset` method runs on resize and updates all the relevant size parameters, since the height can change during a resize.

```suggestion
        this.fullHeight = this.$content.scrollHeight;
```

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 2]
```diff
@@ -52,10 +52,13 @@ export class ReadMoreComponent {
...
+        const collapsedHeight = this.collapsedHeight;
+        const readMoreButtonHeight = this.$readMoreButton ? this.$readMoreButton.offsetHeight : 0;
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/readmore.js:57]: There's a little gotcha here with the `$readMoreButton` height. If the readMoreButton might be hidden when this method is called, the offsetHeight will be zero, even though the button will still have a height once it's made visible! The way we can handle this, is by recording the height of the readMoreButton in the constructor of this class, and updating the height in `reset` if it's non-zero. The readMoreButton is visible, by default when the class is first constructed, so at that point in time, it should have a non-zero height. And then here we can update it.

E.g.

```js
// constructor
this.readMoreHeight = this.$readMoreButton.offsetHeight;

// reset
if (this.$readMoreButton.offsetHeight) {
    this.readMoreHeight = this.$readMoreButton.offsetHeight;
}
```

I think that should handle everything correctly!

**Review by cdrini — CHANGES_REQUESTED** [review]
Nice, great work @CodeMaverick2 ! One small subtle bug here on getting the button's height, but everything else looks great!

**Comment by RayBB** [comment]
@CodeMaverick2 are you still interested in working on this? Drini left a few comments above.

**Comment by CodeMaverick2** [comment]
> @CodeMaverick2 are you still interested in working on this? Drini left a few comments above.

Yes Working on it

**Comment by CodeMaverick2** [comment]
@cdrini @RayBB Changes are done you can review the pr

**Review by cdrini — APPROVED** [review]
Woohoo, nice work folks! Tested and works like butter 🧈
