### PR TITLE
fix/make it possible to add isbn10 with hypens in editing screen

### LINKED ISSUE #6634: Make it possible to add ISBN10 with hyphens in edition editing screen
Related: #4548

Currently, it is not possible to add ISBN10 ID in edition editing screen if it contains hyphens. For example, 966-7007-30-2 can't be added, but if hyphens are deleted it will work fine. In contrast, ISBN13 can be added both with hyphens and without. I think that hyphens can be automatically deleted when adding ISBN to database without need to do it manually.

In my personal opinion, for end user no-hyphen format doesn't look good. Compare 966-7007-30-2 and 9667007302, first one is better distinguishable and it may be preferable for people with bad eyesight. @seabelis suggested having a setting that can be toggled on/off by user to show ISBNs either with hyphens or without

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### PR DESCRIPTION
**Pull request by scottbarnes**
Closes #6634

Fix.

### Technical

On the edit editions page, and with respect to ID Numbers, this:
- allows adding ISBN 10/13 with hyphens and spaces, which are then stripped before passing to the backend;
- won't allow formally invalid ISBNs (i.e. wrong number of characters);
- adds a confirmation for formally valid ISBNs that have an invalid check digit;
- checks for duplicate ISBN entries in the list on the frontend display;
- fixes a small display overflow bug on mobile when a new ISBN was added; and
- fixes a small bug that prevented input error messages (e.g. invalid ISBN) from disappearing once an ID is successfully added.

### Testing

The main testing is found in tests/unit/js/editionsEditPage.test.js, and calls the newly created identifierValidationFunc() found in openlibrary/plugins/openlibrary/js/edit.js to validate each ISBN as it's entered into ID Number form. When a person uses the input form to edit identifiers for an edition, clicking "Add" will:
- not accept ISBNs that are formally invalid (e.g. wrong number of characters);
- confirm adding ISBNs that are formally valid by have an invalid check digit;
- strip hyphens and spaces before sending to the backend, and
- and not let people add duplicate numbers. 

### Screenshot

Attempting to add an invalid ISBN 10
image

The results of clicking "Yes"
image

Attempting to add a duplicate:
image
image

### Stakeholders

@cclauss @hornc 

Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this code which substantially leverage code suggestions, code generation, or code snippets from sources (e.g. Stack Overflow, GitHub) have been annotated with basic attribution so reviewers & contributors may have confidence and access to the correct context to evaluate and use this code.

### CODE REVIEW

**Comment by cclauss** [comment]
Are you able to add some Jest tests to make our GitHub Actions pass?
> Jest: "global" coverage threshold for statements (17%) not met: 16.73%
> Jest: "global" coverage threshold for lines (17%) not met: 16.81%

https://github.com/internetarchive/openlibrary/runs/6950665704?check_suite_focus=true

**Comment by scottbarnes** [comment]
> Are you able to add some Jest tests to make our GitHub Actions pass?
> 
> > Jest: "global" coverage threshold for statements (17%) not met: 16.73%
> > Jest: "global" coverage threshold for lines (17%) not met: 16.81%
> 
> https://github.com/internetarchive/openlibrary/runs/6950665704?check_suite_focus=true

I did write two simple tests that overcome the code coverage failures, but it involved exporting private functions. It makes everything pass, but doesn't fully test the entire process of parsing the ISBNs, checking validity, and checking for duplication.

I have been playing with the ingration testing but am hitting some roadblocks there with the various accounts that uses to run the tests, so I'm still working on that.

Or perhaps there is a better way to test things in jest without (1) exporting each private function and (2) testing the entire process rather than each piece.

**Comment by scottbarnes** [comment]
I see I have made a complete hash of the commit history. So much for being clever. I will see what I can do to fix this.

File: openlibrary/plugins/openlibrary/js/edit.js [hunk 1]
```diff
@@ -70,30 +70,163 @@ export function initRoleValidation() {
...
+ * @returns true if the given ISBN is already added to the edition
+ */
+function isIsbnDupe(isbn) {
+    const isbnEntries = document.querySelectorAll('.isbn_10, .isbn_13');
+    for (let i = 0; i < isbnEntries.length; i++) {
+        if (isbn === isbnEntries[i]['value']) {
+            return true;
+        }
+    }
+    return false;
```
Comment (RayBB) [inline openlibrary/plugins/openlibrary/js/edit.js:86]: You may want to use more modern JS syntax like the Array.some() function. 
It might look like this:
`return isbnEntries.some(entry => entry['value'] === isbn)`


https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

File: openlibrary/plugins/openlibrary/js/edit.js [hunk 2]
```diff
@@ -70,30 +70,163 @@ export function initRoleValidation() {
...
+}
+
+/**
+ * isChecksumValidIsbn10 checks the format and validation for ISBN 10.
+ * Adapted from https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s13.html
+ * @params isbn - ISBN string for validating
+ * @returns true if ISBN string is a valid ISBN 10
+ */
+export function isChecksumValidIsbn10(isbn) {
```
Comment (RayBB) [inline openlibrary/plugins/openlibrary/js/edit.js:95]: We could import books with isbns that don't have a valid checksum.
It's known that books sometimes are published with "invalid" isbns https://en-academic.com/dic.nsf/enwiki/8948#cite_ref-18

But I imagine we still want to import them.

So, I'm not sure how/if we should use it. Perhaps it could be a warning ("this looks like an invalid isbn, are you sure you want to continue?")?

**Review by RayBB — COMMENTED** [review]
Disclaimer: I am not a maintainer of Open Library. However, I have contributed with some frequency. I'm guessing I was tagged in this review because I've touched some related code.

I haven't done a through review like I'm sure one of the staff members will.

However, I am offering two small comments that may help move along the process.
I also offer a note of appreciation for your contribution :)

File: openlibrary/plugins/openlibrary/js/edit.js (hunk 1 above)
Comment (scottbarnes) [reply openlibrary/plugins/openlibrary/js/edit.js:86]: I appreciate this and will update the code. Thanks for the input on how I can make it better. :)

File: openlibrary/plugins/openlibrary/js/edit.js (hunk 2 above)
Comment (scottbarnes) [reply openlibrary/plugins/openlibrary/js/edit.js:95]: Oh, thank you for catching this. I will see what I can do.

**Comment by scottbarnes** [comment]
I attempted to incorporate @RayBB's suggestion to update to slightly more modern JavaScript in three places. Additionally, to address the issue of ISBNs that may be invalid, the check now works as follows:

1. First there is a test for formal validity (e.g. correct number of characters, no letters aside from X in ISBN 10, etc.).
2. Then there is a second test for the ISBN check digit.
3. If an ISBN passes the formality test but fails the on the check digit, the user is prompted to add the ISBN anyway.

I also increased the max bundlesize for static/build/user-website.*.js to 3.2KB from 3KB.

Note: the tests do NOT currently test whether the invalid check digit override actually works, as I am having trouble testing this. This is obviously significant and I am working to address that.

Some screenshots:
Attempting to add an invalid ISBN 10
image

The results of clicking "Yes"
image

**Comment by scottbarnes** [comment]
@cclauss, @cdrini, @jimchamp: I updated the original comment in this thread, and from my perspective this is ready to be reviewed. I have updated the testing to cover, I think, the full functionality of what's been added. I'm more than happy to do whatever is required to get this right. :)

I am not sure if writing to sessionStorage was the 'right' way to handle state here. I struggled with that a bit and wasn't sure where to reach out for that, though I am guessing questions like that will be easier to resolve when I gain access to the Slack server.

I also am not sure if the way I consolidated the commits and force pushed is going against best practices here.

**Comment by scottbarnes** [comment]
Thanks for this, @jimchamp. I'll get on this and reach out if I run into any issues. :)

**Comment by scottbarnes** [comment]
I seem to have done something to cause pre-commit.ci to commit other files ([ad36e5f](https://github.com/internetarchive/openlibrary/pull/6670/commits/ad36e5f433095887487a3041fc32890dfc4bac56)), but I'm stuck on how to remove that.

With respect to the failing test (excerpted below), that was showing up for a time on my local branch, and I was trying to investigate webpack, but now I can't replicate it locally, and to my knowledge I didn't change anything. I have nothing to commit and my latest changes are pushed, yet I no longer get this error on ```docker-compose run --rm home npm run test```, so I am puzzled there too. For a while, within the 'home' docker container, ```npm run build-assets:webpack``` wasn't building user-website.[hash].js, though now it does. I see it doesn't on the test server.

I'm open to any ideas how how to address either issue.

```
Test Suites: 15 passed, 15 total
Tests:       201 passed, 201 total
Snapshots:   0 total
Time:        12.455 s
Ran all test suites.
 ERROR  There is no matching file for static/build/user-website.*.js in /home/runner/work/openlibrary/openlibrary 
Error: Process completed with exit code 1.
```

**Comment by cclauss** [comment]
The broken build was my fault.  Sorry.  If you try again things should be better.

**Comment by cclauss** [comment]
@jimchamp `remove_labels` might not work for users who are not repo maintainers.

**Comment by scottbarnes** [comment]
The pre-commit thing is all sorted; thanks! Now it's just on me to try to replicate ```ERROR  There is no matching file for static/build/user-website.*.js in /home/runner/work/openlibrary/openlibrary``` once again so that I can try to figure out what's causing it. :)

**Comment by jimchamp** [comment]
> @jimchamp `remove_labels` might not work for users who are not repo maintainers.

Have opened #6757 to remove the failing action.

**Comment by jimchamp** [comment]
> The pre-commit thing is all sorted; thanks! Now it's just on me to try to replicate `ERROR There is no matching file for static/build/user-website.*.js in /home/runner/work/openlibrary/openlibrary` once again so that I can try to figure out what's causing it. :)

I'm seeing this locally when I run your `docker-compose exec web npm run test` with your latest code.  The `isbnOverride` export is affecting webpack's code splitting such that the `user-website.${random_hash}.js` files are not being created.  `user-website.*.js` files are generated when `edit.js` is transpiled.

I don't know enough about webpack to give a "correct" solution to this issue.  However, moving `isbnOverride` to it's own file, and then importing it where needed solved the issue for me.

**Comment by scottbarnes** [comment]
Thank you, @jimchamp! I will clean this up today.

**Review by jimchamp — APPROVED** [review]
I put this on testing, and everything seems to be working properly.  Thanks @scottbarnes!
