### PR TITLE
fix: Add ARIA attributes and roles to print disability dynamic section 

### LINKED ISSUE #10801: Add ARIA roles and attributes to account registration page
### Problem

Dynamic sections of the account registration form lack ARIA roles and attributes, likely hindering navigation for patrons using screen readers.

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

### Breakdown

@jimchamp to provide a breakdown of requirements

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by mystic-06**
Closes #10801

**Fix**  

### Technical
- Added `aria-expanded` and `aria-controls` to the print disability checkbox  
- Added `role="region"`, `aria-hidden`, and `aria-labelledby` to the dropdown container  
- Added `aria-describedby`, `aria-required`, and `aria-invalid` to the program selector  
- Added `role="alert"` + `aria-live="polite"` for error messaging  
- Updated JS to toggle ARIA states dynamically (expanded/hidden/required/invalid) based on checkbox state  
- Added safety null checks to avoid JS errors when elements are not present

### Testing
- Tested with Orca on Linux (CachyOS/GNOME)
- Verified ARIA state changes through browser DevTools  
- Confirmed error messages are announced correctly  
- Checked keyboard navigation (Tab/Space/Enter/Arrow keys)  
- All existing unit tests pass

### CODE REVIEW

**Comment by mystic-06** [comment]
Hi @jimchamp ! I know maintainers are busy, but I wanted to check in on this PR.  
If there’s any feedback or anything I might have missed, I'd be glad to address it.
Thank you!

File: openlibrary/plugins/openlibrary/js/signup.js [hunk 1]
```diff
@@ -159,16 +159,22 @@ export function initSignupForm() {
     }
 
     function validatePDSelection() {
+        if (!rpdCheckbox || !pdaSelector) {
+            return;
+        }
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/signup.js]:
```suggestion
```
Why did you add this?  The checkbox and selector are always present in the registration form.

File: openlibrary/plugins/openlibrary/js/signup.js [hunk 2]
```diff
@@ -207,10 +213,23 @@ export function initSignupForm() {
     })
 
     function updateSelectorVisibility() {
+        if (!rpdCheckbox || !pdaSelectorContainer) {
+            return;
+        }
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/signup.js]:
```suggestion
```

File: openlibrary/templates/account/create.html [hunk 3]
```diff
@@ -80,17 +80,17 @@ <h1 class="ol-signup-hero__title">$_("Sign Up")</h1>
                 <label for="ia_newsletter">$:_('I want to receive news, announcements, and resources from the <a href="https://archive.org/">Internet Archive</a>, the non-profit that runs Open Library.')</label>
             </div>
             <div id="rpd-checkbox" class="ol-signup-form__checkbox">
-                <input type="checkbox" id="pd_request" name="pd_request"/>
-                <label for="pd_request">$:_('I want to apply* for <a href="https://help.archive.org/help/program-overview/" target="_blank">special print disability access</a> through a qualifying program.')</label>
+                <input type="checkbox" id="pd_request" name="pd_request" aria-expanded="false" aria-controls="pda-selector"/>
+                <label for="pd_request" id="pd_request_label">$:_('I want to apply* for <a href="https://help.archive.org/help/program-overview/" target="_blank">special print disability access</a> through a qualifying program.')</label>
```
Comment (jimchamp) [inline openlibrary/templates/account/create.html]:
```suggestion
                <label for="pd_request" id="pd-request-label">$:_('I want to apply* for <a href="https://help.archive.org/help/program-overview/" target="_blank">special print disability access</a> through a qualifying program.')</label>
```
HTML class names and IDs should be written using kebab-case.

File: openlibrary/templates/account/create.html [hunk 4]
```diff
@@ -80,17 +80,17 @@ <h1 class="ol-signup-hero__title">$_("Sign Up")</h1>
...
             </div>
-            <div id="pda-selector" class="ol-signup-form__select hidden">
-                <div class="ol-signup-form__error" id="pd_programMessage"></div>
-                <select id="pd_program" name="pd_program" aria-label="$_('Select qualifying program')">
+            <div id="pda-selector" class="ol-signup-form__select hidden" role="region" aria-labelledby="pd_request_label" aria-hidden="true">
```
Comment (jimchamp) [inline openlibrary/templates/account/create.html]:
```suggestion
            <div id="pda-selector" class="ol-signup-form__select hidden" role="region" aria-labelledby="pd-request-label" aria-hidden="true">
```

File: openlibrary/plugins/openlibrary/js/signup.js [hunk 5]
```diff
@@ -207,10 +213,23 @@ export function initSignupForm() {
...
         if (rpdCheckbox.checked) {
             pdaSelectorContainer.classList.remove('hidden')
+            rpdCheckbox.setAttribute('aria-expanded','true')
+            pdaSelectorContainer.setAttribute('aria-hidden','false')
+            if (pdaSelector) {
+                pdaSelector.setAttribute('aria-required', 'true')
+            }
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/signup.js]:
```suggestion
            pdaSelector.setAttribute('aria-required', 'true')
```

File: openlibrary/plugins/openlibrary/js/signup.js [hunk 6]
```diff
@@ -207,10 +213,23 @@ export function initSignupForm() {
...
         } else {
             pdaSelectorContainer.classList.add('hidden')
+            rpdCheckbox.setAttribute('aria-expanded','false')
+            pdaSelectorContainer.setAttribute('aria-hidden','true')
+            if (pdaSelector) {
+                pdaSelector.setAttribute('aria-required', 'false')
+            }
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/signup.js]:
```suggestion
            pdaSelector.setAttribute('aria-required', 'false')
```

**Comment by mystic-06** [comment]
Thanks for the review and for the feedback!
I’ll update the newly added HTML classes and IDs to use kebab-case and remove the guard checks as suggested. I’ll push an updated commit shortly.

File: openlibrary/plugins/openlibrary/js/signup.js (hunk 1 above)
Comment (mystic-06) [reply openlibrary/plugins/openlibrary/js/signup.js]: I originally added the guards because they were needed to keep the existing test cases passing, but I’ll remove them as suggested.

**Comment by mystic-06** [comment]
Thanks for the feedback! I’ve fixed the related tests. Please let me know if anything else needs tweaking.

@jimchamp

**Comment by mystic-06** [comment]
Hi @jimchamp ! Just checking on the status of this PR — please let me know if anything is needed from my side. Thanks!

**Review by jimchamp — APPROVED** [review]
Thanks @mystic-06!
