### PR TITLE
6558/bugfix/fix 50 edition merging bug

### LINKED ISSUE #6558: Don't allow merging a work with more than 50 editions into another work
Sub-task of #6556

The Merge UI currently allows this, but only moves over the first 50 editions! Leaving the rest in a sort of limbo.

Prevent this from being allowed, or investigate if we can increase it to a larger limit, but we'll probably still need to block at whatever limit that is.

### Stakeholders
@mheiman @dcapillae

### PR DESCRIPTION
**Pull request by mheiman**
Closes #6558

Addresses the problem of bad merges when the MergeUI doesn't retrieve all of the editions for a work. 

### Technical
- Increases the limit for retrieved editions from 50 to 200
- Identifies any works (other than the primary work) where the number of editions retrieved is less than the total number of editions and blocks the merge if that condition exists.

### Testing
Try this merge:
https://testing.openlibrary.org/works/merge?records=OL99529W,OL27228774W,OL28078149W,OL28101686W,OL28124222W,OL28139422W
Set the primary work to something other than the first entry on the list to trigger the error condition.

### Stakeholders
@mheiman @cdrini

### CODE REVIEW

File: openlibrary/components/MergeUI/MergeTable.vue [hunk 1]
```diff
@@ -153,6 +153,16 @@ export default {
             );
         },
 
+        async find_unretrieved_editions() {
+            if (!this.master_key || !this.records || !this.editions)
+                return undefined;
+            const filtered_works = this.records
+                .filter(work => work.type.key === '/type/work' &&
+                work.key !== this.master_key &&
+                this.editions[work.key].entries.length < this.editions[work.key].size);
```
Comment (cdrini) [inline openlibrary/components/MergeUI/MergeTable.vue:162]: Ahhhh `size` is the total number of editions! Nice!

File: openlibrary/components/MergeUI.vue [hunk 2]
```diff
@@ -62,9 +62,14 @@ export default {
         async doMerge() {
             if (!this.$refs.mergeTable.merge) return;
             const { record: master, dupes, editions_to_move } = this.$refs.mergeTable.merge;
+            const unretrieved_editions_works = await this.$refs.mergeTable.find_unretrieved_editions;
 
             this.mergeStatus = 'Saving...';
             try {
+                if (unretrieved_editions_works.length)
+                {
+                    throw new Error(`Could not merge: ${unretrieved_editions_works.join(', ')} has more than ${default_edition_limit} editions.`);
```
Comment (cdrini) [inline openlibrary/components/MergeUI.vue:71]: We also want to alert here so the user gets the error.
```suggestion
                    alert(`Could not merge: ${unretrieved_editions_works.join(', ')} has more than ${default_edition_limit} editions.`);
                    throw new Error(`Could not merge: ${unretrieved_editions_works.join(', ')} has more than ${default_edition_limit} editions.`);
```

File: openlibrary/components/MergeUI/MergeTable.vue [hunk 3]
```diff
@@ -153,6 +153,16 @@ export default {
             );
         },
 
+        async find_unretrieved_editions() {
```
Comment (cdrini) [inline openlibrary/components/MergeUI/MergeTable.vue:156]: This is a `computed`, so behaves like a property more than a function actually. So we don't want to name it as a verb, because that makes it seem like a function, when it's more of a property with a backing getter.

And we're not retrieving editions, we're retrieving the works, so `unmergeable_works` seems like a better name.

```suggestion
        async unmergeable_works() {
```

File: openlibrary/components/MergeUI.vue [hunk 4]
```diff
@@ -62,9 +62,14 @@ export default {
         async doMerge() {
             if (!this.$refs.mergeTable.merge) return;
             const { record: master, dupes, editions_to_move } = this.$refs.mergeTable.merge;
+            const unretrieved_editions_works = await this.$refs.mergeTable.find_unretrieved_editions;
```
Comment (cdrini) [inline openlibrary/components/MergeUI.vue:65]: We shouldn't need to await here; `asyncComputed` does magic behind the scenes.
```suggestion
            const unretrieved_editions_works = this.$refs.mergeTable.find_unretrieved_editions;
```

File: openlibrary/components/MergeUI/MergeTable.vue (hunk 3 above)
Comment (cdrini) [reply openlibrary/components/MergeUI/MergeTable.vue:156]: Actually, I think it's clearer if we put this logic inside the `merge` data structure. So we can have a field of `unmergeable_works` inside the return of the `async merge` function.

**Review by cdrini — CHANGES_REQUESTED** [review]
Approach looks good! Some code quality/naming stuff. I think it would be best if we put the logic of `find_unretrieved_editions` inside the `merge` function, and have that return `unmergeable_works` as part of its object. The data structure from `merge` is meant to be kind of a holistic summary of everything, and that makes sense to live in there :+1:

Most of my comments don't super apply if that's done :P

**Review by cdrini — APPROVED** [review]
Code lgtm! Testing now...

**Review by cdrini — APPROVED** [review]
Tested locally with /works/merge?records=OL99529W,OL27228774W,OL28078149W,OL28101686W,OL28124222W,OL28139422W :


`PYTHONPATH=. scripts/copydocs.py --editions /works/OL99529W /works/OL27228774W /works/OL28078149W /works/OL28101686W /works/OL28124222W /works/OL28139422W `

It errored when trying to merge something with more than 200 editions; it did not otherwise
