### PR TITLE
Fix reading log dropdown toggling

### LINKED ISSUE #6530: Reading Log menu doesn't close after adding book to list
### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### PR DESCRIPTION
**Pull request by jimchamp**
Closes #6530

Removed redundant `toggleDropper()` function.  This was interfering with other code in `ol.js` that toggled the droppers.  Droppers should now behave as they did before the list widget refactor.

### Technical

`ol.js` seems to be a catch-all file that contains JS that was previously inlined.  I moved all dropper-related code from `ol.js` to a new `/droppers/index.js` file.

Since the `ol.test.js` only contained a test for the dropper, I have renamed the file `droppers.test.js`.

### Stakeholders

@DebbieSan 
@mekarpeles

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/droppers/index.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+    for (const dropper of dropperElements) {
+        droppers.push(dropper)
+
+        $(dropper).on('click', '.dropclick', debounce(function() {
+            $(this).next('.dropdown').slideToggle(25);
+            $(this).parent().next('.dropdown').slideToggle(25);
+            $(this).parent().find('.arrow').toggleClass('up');
+        }, 300, false))
+
+        $(dropper).on('click', '.dropper__close', debounce(function() {
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/droppers/index.js:33]: I've added the `dropper__close` class to dropper affordances that, when clicked, should close the dropper (reading log actions and adding to a list).
The concept of closing a dropper by clicking on an element with class `dropper__close` is meant to be short-lived.  I'm planning on creating a generic dropper component, and will have a solution for closing the droppers that improves the separation of concerns between a dropper and its contents.
