### PR TITLE
Remove inline Javascript from interstitial template

### LINKED ISSUE #10650: Remove inline Javascript from interstitial page
### Problem / Opportunity

The new interstitial page contains inline Javascript that closes the current tab when a `Cancel` link is clicked.  This code should be moved to Webpack.

### Proposal

1. Add a unique class name or identifier to the [cancel link](https://github.com/internetarchive/openlibrary/blob/bf7d944f51c3ef0444a768f0c30c8a085d7e0ddf/openlibrary/templates/interstitial.html#L14), and remove the `onclick` attribute.
2. In [`initInterstitial()`](https://github.com/internetarchive/openlibrary/blob/bf7d944f51c3ef0444a768f0c30c8a085d7e0ddf/openlibrary/plugins/openlibrary/js/interstitial.js#L1), add a click listener that closes the current tab to the close link.

### Related files

Refer to [this map of common Endpoints](https://github.com/internetarchive/openlibrary/wiki/Endpoints):
Related files are in the "Proposal" section, above.

### Requirements Checklist
Checklist of requirements that need to be satisfied in order for this issue to be closed:
* [ ] Inline interstitial code has been moved to Webpack with no regressions

### Stakeholders

*

<hr>

### Instructions for Contributors

* **Before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) or pushing up changes to a PR, please first [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date, as the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by LalitNarayanYadav**
Closed #10650

## Changes
- Removed inline JavaScript from cancel button
- Added delegated event listener in `initInterstitial()`
- Implemented proper timer cleanup
- Added error handling for `window.close()`

## Testing
- [x] Cancel button closes window (popup) or redirects (regular tab)
- [x] Countdown timer works until automatic redirect
- [x] No console errors in Chrome/Firefox/Edge

### CODE REVIEW

**Review by jimchamp — CHANGES_REQUESTED** [review]
@LalitNarayanYadav, you've made a lot of changes that were out of scope for #10650 --- those changes will have to be rolled back before this is merged.  More importantly, the code has to work before it is merged.

Please update this PR with the suggested changes.  Ensure that you've tested the code before pushing your updates.

**Comment by jimchamp** [comment]
@LalitNarayanYadav, when contributing to this or any other repo, use the PR or issue template that was provided by the maintainers.  I'm going to begin closing PRs that don't follow our template.

**Review by LalitNarayanYadav — COMMENTED** [review]
@jimchamp Thanks for the feedback! I've reverted the previous changes and now only included the cancel button functionality using a .close-window class and event listener. Let me know if anything else needs tweaking

File: openlibrary/plugins/openlibrary/js/interstitial.js [hunk 1]
```diff
@@ -10,4 +10,12 @@ export function initInterstitial(elem) {
             window.location.href = url
         }
     }, 1000) // 1 second interval
+
+    // Add cancel button handler
+    const cancelButton = elem.querySelector('.close-window');
+    if (cancelButton) {
+        cancelButton.addEventListener('click', (e) => {
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/interstitial.js:17]:
```suggestion
        cancelButton.addEventListener('click', () => {
```
Remove unused variable

**Review by jimchamp — APPROVED** [review]
Thanks @LalitNarayanYadav!  This is working great.  I'm going to make a small commit to fix a linting issue that's preventing our workflows from passing, then I'll merge this.
