### PR TITLE
[Bug Fix] Prevent the expanding/collapsing of the subject area when the link is being clicked

### LINKED ISSUE #6361: Make subjects + arrow clickable (expand/collapse) but not the subject tags itself
The subject tags simultaneously collapse/expand the subject area AND navigate away from the page. This is potentially unclear for patrons.
### Evidence / Screenshot (if possible)
expanded_subjects

_This behavior is incorrect.  Subjects should not expand or collapse when link is clicked._
### Steps to Reproduce

1. Go to ...Any work page.
2. Do ...Click a subject tag

* Actual: As described above.
* Expected: Subject tags should not trigger expand/collapse behaviour. This should be limited to the arrow expanders.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@jimchamp

### PR DESCRIPTION
**Pull request by dbouris**
Closes #6361 

With this fix, we achieve preventing collapsing and expanding of the subject area while a link from the `a` tag in being clicked.

### Technical
We attached to the jQuery click event handler an argument  in order to check if the nodeName of the tag is `a`. If this is true, there is no need to expand/collapse and the user should be redirected to the corresponding page.

### Testing
On the book page, click a link on the Subjects, People or Pages. The list expands which is an incorrect behavior before redirecting. 

### Screenshot

https://user-images.githubusercontent.com/72794144/163714964-4c56e6e4-c22b-4b29-83ac-1815bdb93257.mp4

### Stakeholders

@cdrini 
@jimchamp 

Attribution Disclaimer: By proposing this pull request, I affirm to have made a best-effort and exercised my discretion to make sure relevant sections of this code which substantially leverage code suggestions, code generation, or code snippets from sources (e.g. Stack Overflow, GitHub) have been annotated with basic attribution so reviewers & contributors may have confidence and access to the correct context to evaluate and use this code.

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 1]
```diff
@@ -1,18 +1,18 @@
 export function initReadMoreButton() {
-    $('.read-more-button').on('click',function(){
+    $('.read-more-button').on('click', function () {
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/readmore.js:2]:
```suggestion
    $('.read-more-button').on('click',function(){
```
Let's not change any unrelated code.

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 2]
```diff
@@ -1,18 +1,18 @@
...
         const up = $(this).parent().parent();
         $(`.${up.attr('class')}-content`).removeClass('restricted-height', 300);
         $(`.${up.attr('class')}.read-more`).addClass('hidden');
         $(`.${up.attr('class')}.read-less`).removeClass('hidden');
     });
-    $('.read-less-button').on('click',function(){
+    $('.read-less-button').on('click', function () {
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/readmore.js:8]:
```suggestion
    $('.read-less-button').on('click',function(){
```

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 3]
```diff
@@ -1,18 +1,18 @@
...
         const up = $(this).parent().parent();
         $(`.${up.attr('class')}-content`).addClass('restricted-height', 300);
         $(`.${up.attr('class')}.read-more`).removeClass('hidden');
         $(`.${up.attr('class')}.read-less`).addClass('hidden');
     });
-    $('.restricted-view').each(function() {
-        if ($(this).outerHeight()<50) {
+    $('.restricted-view').each(function () {
+        if ($(this).outerHeight() < 50) {
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/readmore.js:15]:
```suggestion
    $('.restricted-view').each(function() {
        if ($(this).outerHeight()<50) {
```

File: openlibrary/plugins/openlibrary/js/readmore.js [hunk 4]
```diff
@@ -29,15 +29,23 @@ export function initClampers(clampers) {
...
+                    if (up.hasClass('clamp')) {
+                        up.css({ display: up.css('display') === '-webkit-box' ? 'unset' : '-webkit-box' });
+
+                        if (up.attr('data-before') === '\u25BE ') {
+                            up.attr('data-before', '\u25B8 ')
+                        } else {
+                            up.attr('data-before', '\u25BE ')
+                        }
                     }
                 }
```
Comment (jimchamp) [inline openlibrary/plugins/openlibrary/js/readmore.js:50]:
```suggestion
                }

                if (up.hasClass('clamp')) {
                    up.css({ display: up.css('display') === '-webkit-box' ? 'unset' : '-webkit-box' });

                    if (up.attr('data-before') === '\u25BE ') {
                        up.attr('data-before', '\u25B8 ')
                    } else {
                        up.attr('data-before', '\u25BE ')
                    }
                }
```
No need for an `else` block here, since we are returning in the `if` block on line 37.

**Review by jimchamp — CHANGES_REQUESTED** [review]
This should be good to merge once the requested changes have been made.

**Comment by Philippos01** [comment]
@jimchamp we commited the proposed changes.

**Review by cdrini — APPROVED** [review]
Lgm! Tested on gitpod. Clicking header expands. Clicking anchor does not. Yaaay unit tests!

**Comment by cdrini** [comment]
Talked with @jimchamp ; taking this to try to get it in today's deploy :+1:
