### PR TITLE
Instant search result box corrected

### LINKED ISSUE #780: resizing OL small and then wide w/ text in searchbox causes dropdown to trigger
The primary searchbox in our topmost header bar on OpenLibrary.org (which also contains our logo) experiences problems when the the width of the website is changed.

**Steps to reproduce:**
1. Load OpenLibrary.org on Desktop (not a mobile device) with a browser opened to > 800px
2. Enter the text "Lord of the Rings" into the primary search box and **do not** press enter. You should see `realtime instant results` appear
3. Click outside of the primary searchbox and the `realtime instant results` should disappear / hide
4. Resize the browser window < 400px.
5. Resize the browser window back to > 800px
6. An error is occuring where The `realtime instant results` suddenly become shown again

**Hypothesis:**
There is code in `openlibrary/plugins/openlibrary/js/ol.js` which handles how the primary searchbox should behave when the window is resized. This may accidentally be showing `realtime instant results` when it shouldn't be.

### PR DESCRIPTION
**Pull request by rohitjain00**
> **Description**: hotfix

Closes #780

> **Technical**: What should be noted about the implementation?
A variable instantSearchResultState was added to save the state of the search result box. On resizing the window it restores itself to the last state it was it

> **Testing**: 
1. Load OpenLibrary.org on Desktop (not a mobile device) with a browser opened to > 800px
2. Enter the text "Lord of the Rings" into the primary search box and do not press enter. You should see realtime instant results appear
3. Click outside of the primary searchbox and the realtime instant results should disappear / hide
4. Resize the browser window < 400px.
5. Resize the browser window back to > 800px
6. realtime instant results restores to its previous state

### CODE REVIEW

**Comment by mekarpeles** [comment]
lgtm, will load on dev and verify

File: openlibrary/plugins/openlibrary/js/ol.js [hunk 1]
```diff
@@ -255,7 +258,7 @@ $(function(){
         };
     };
 
-    $(document).on('submit','.trigger', function(e) {
```
Comment (mekarpeles) [inline openlibrary/plugins/openlibrary/js/ol.js]: this line shouldn't have been changed, cc: @ShreyashApp this was the cause of the regression to your fix :)

Comment (rohitjain00) [reply openlibrary/plugins/openlibrary/js/ol.js]: That was done by mistake. Thanks @mekarpeles  for pointing it out for me.
