### PR TITLE
Handle orphaned editions passed to MergeUI record enhancer

### LINKED ISSUE #10966: Cannot merge works if a work has no author
### Reproducing the bug

1. Go to https://openlibrary.org/works/merge?records=OL16305918W,OL20650159W,OL19635988W

* Expected behavior: The works are listed
* Actual behavior: There is an error and nothing is rendered

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### LINKED ISSUE #11702: Orphaned editions passed to MergeUI crashing script
### Problem

MergeUI will crash if passed orphaned editions that have an **authors** field.  The merge process doesn't actually care, but the enhancement that was added to display author names doesn't take into account the different **authors** field structures between works and editions.

### Reproducing the bug

Here's an example of a merge that crashes the interface:

[https://openlibrary.org/works/merge?records=OL14857756W,OL24198259M](https://openlibrary.org/works/merge?records=OL14857756W,OL24198259M)

You can see the errors in the console.

### Context

- Browser (Chrome, Safari, Firefox, etc): N/A
- OS (Windows, Mac, etc): N/A
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
All that's required is adding code to handle the difference in author data between works and editions. I'll be making a pull request shortly.

#### Stakeholders

@mheiman 
<hr>

### PR DESCRIPTION
**Pull request by mheiman**
Closes #11702 . Partially fixes #10966

Fixes the issue where MergeUI will crash if passed orphaned editions that have an authors field. 

### Technical
Limits author lookups to records with work-style authors fields.

Since edition authors aren't added to the primary work during merging, I'm not giving them the enhanced display that work authors get.

### Testing
On testing you should be able to load https://openlibrary.org/works/merge?records=OL14857756W,OL24198259M and not crash MergeUI.

### Stakeholders
@mheiman

### CODE REVIEW

File: openlibrary/components/MergeUI/utils.js [hunk 1]
```diff
@@ -263,13 +265,15 @@ function save_many(items, comment, action, data) {
...
+ * Fetches name associated with the author key (ignores editions)
  * @param {Object[]} works
  * @returns {Promise<Record<string,object>} A response to the request
  */
 export async function get_author_names(works) {
     const authorIds = _.uniq(works).flatMap(record =>
-        (record.authors || []).map(authorEntry => authorEntry.author.key)
+        (record.authors || [])
+            .filter(authorEntry => authorEntry.author && authorEntry.author.key)
+            .map(authorEntry => authorEntry.author.key)
```
Comment (cdrini) [inline openlibrary/components/MergeUI/utils.js]: The fact that the shape of author entries differs between works/editions is unexpected, and something we should avoid relying on, since it'll cause confusion. Supporting both everywhere seems clearer.

```suggestion
            .map(authorEntry => authorEntry.author?.key ?? authorEntry.key)
```

File: openlibrary/components/MergeUI/MergeTable.vue [hunk 2]
```diff
@@ -159,7 +159,10 @@ export default {
 
             for (const record of enhanced_records) {
                 for (const entry of (record.authors || [])) {
-                    entry.name = author_names[entry.author.key.slice('/authors/'.length)];
+                    // Only process work records {author: {key: "..."}}
+                    if (entry.author && entry.author.key) {
+                        entry.name = author_names[entry.author.key.slice('/authors/'.length)];
+                    }
```
Comment (cdrini) [inline openlibrary/components/MergeUI/MergeTable.vue]:
```suggestion
                    // Support both author entry shapes: {author: {key: "..."}}, {key: "..."}
                    const authorKey = entry.author?.key ?? entry.key;
                        entry.name = author_names[authorKey.slice('/authors/'.length)];
                    }
```

File: openlibrary/components/MergeUI/utils.js [hunk 3]
```diff
@@ -263,13 +265,15 @@ function save_many(items, comment, action, data) {
 }
 
 /**
- * Fetches name associated with the author key
+ * Fetches name associated with the author key (ignores editions)
```
Comment (cdrini) [inline openlibrary/components/MergeUI/utils.js]:
```suggestion
 * Fetches name associated with the author key
```

**Review by cdrini — APPROVED** [review]
Lgtm! One change to avoid relying on the differing author shape between works/editions ; if we want to handle them separately, we should specifically check the object type. But in these cases I think it's ok if they're seen the same.

File: openlibrary/components/MergeUI/MergeTable.vue [hunk 4]
```diff
@@ -159,7 +159,10 @@ export default {
 
             for (const record of enhanced_records) {
                 for (const entry of (record.authors || [])) {
-                    entry.name = author_names[entry.author.key.slice('/authors/'.length)];
+                    // Support both author entry shapes: {author: {key: "..."}}, {key: "..."}
+                    const authorKey = entry.author?.key ?? entry.key;
+                        entry.name = author_names[authorKey.slice('/authors/'.length)];
+                    }
```
Comment (cdrini) [inline openlibrary/components/MergeUI/MergeTable.vue]:
```suggestion
                    // Support both author entry shapes: {author: {key: "..."}}, {key: "..."}
                    const authorKey = entry.author?.key ?? entry.key;
                    entry.name = author_names[authorKey.slice('/authors/'.length)];
```

File: openlibrary/components/MergeUI/MergeTable.vue [hunk 5]
```diff
@@ -159,7 +159,9 @@ export default {
 
             for (const record of enhanced_records) {
                 for (const entry of (record.authors || [])) {
-                    entry.name = author_names[entry.author.key.slice('/authors/'.length)];
+                    // Support both author entry shapes: {author: {key: "..."}}, {key: "..."}
+                    const authorKey = entry.author?.key ?? entry.key;
```
Comment (cdrini) [inline openlibrary/components/MergeUI/MergeTable.vue:163]:
```suggestion
                    const authorKey = entry.author?.key ?? entry.key;
                    if (!authorKey) continue;
```

**Comment by cdrini** [comment]
Tested on testing and worked like a charm! This also partially addressed the issue with work authors being malformatted and missing
