### PR TITLE
Disable autocomplete requests for search inside

### LINKED ISSUE #3285: Search bar autocomplete tries hit /search/inside
Noticed while testing #3283 that every time a character is typed when "Text" is selected, that a _very slow and expensive_ request is made to /search/inside.json. This has no perceivable effect on UX, but the call to IA's FTS is expensive and should not be hit so frequently. The actual perf hit of this is likely small since I imagine a very small fraction of our userbase has the search dropdown set to "inside", but even one person would be triggering a ridiculous amount of requests to this endpoint.

### Steps to Reproduce
1. Go to https://openlibrary.org
2. Selected "Text" in the search drop down
3. Start typing

* Actual: Requests made to /search/inside.json
* Expected: No requests made while typing for this endpoint

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF74
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@gdamdam @mekarpeles

### PR DESCRIPTION
**Pull request by cdrini**
Closes #3285. Although /search/inside.json isn't defined, it hits the regular /search/inside endpoint! So each character typed while "Text" was selected would trigger a _very_ expensive call to IA's FTS.

### Technical
Nothing to note.

### Testing
- ✅ Typing in search box with "Title" selected shows autocomplete
- ✅ Typing in search box with "Text" selected makes no network requests

### Evidence
No ui changes.

### Stakeholders
@mekarpeles @gdamdam

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/ol.js [hunk 1]
```diff
@@ -74,18 +74,19 @@ export default function init(){
     }
 
     renderInstantSearchResults = function(q) {
-        var facet_value = searchFacets[localStorage.getItem('facet')];
-        var url, facet;
+        const facet_value = searchFacets[localStorage.getItem('facet')];
+        // Not implemented; also, this call is _expensive_ and should not be done!
+        if (facet_value === 'inside') return;
```
Comment (jdlrobson) [inline openlibrary/plugins/openlibrary/js/ol.js]: I'd prefer us to always wrap the if statements in curly braces but clearly our eslinter is not doing that right now and that's a conversation for a later date.

**Comment by jdlrobson** [comment]
Thanks @cdrini !
