### PR TITLE
Fix author page lists not loading

### LINKED ISSUE #11085: Lists on author pages do not load
### Problem

Lists on author pages do not load.

Image

### Reproducing the bug

1. Go to ... and author page
2. Do ... try to add to one of your lists

* Expected behavior: lists load and work as usual
* Actual behavior: lists do not load

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

### PR DESCRIPTION
**Pull request by jimchamp**
Closes #11085

Addresses bug which prevents lists from loading on author and orphaned edition pages.

### Technical

The My Books Droppers that are rendered on author page sidebars are not associated with a work ID (the same is true for droppers on orphaned edition pages).  The HTML for the check-in components is not rendered for these droppers, as check-ins require a work ID.

Whenever `this.checkInComponents.initialize()` was called by a dropper that didn't include the check-in HTML, it threw an exception that prevented the [`initMyBooksAffordances`](https://github.com/internetarchive/openlibrary/blob/baf7303c2ee8d14c68ce02bb7f0232f467496e53/openlibrary/plugins/openlibrary/js/my-books/index.js#L10C17-L10C39) function from fetching the list data and updating the view.

Now, if there is no check-in HTML included with a dropper, we set `this.checkInComponents` to `null` and check for the object before calling `initialize()`.  This null check is only needed here, as it is present in all other places where `this.checkInComponents` is referenced.

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper.js [hunk 1]
```diff
@@ -86,7 +90,9 @@ export class MyBooksDropper extends Dropper {
 
         this.readingLogForms.initialize()
         this.readingLists.initialize()
-        this.checkInComponents.initialize()
+        if (this.checkInComponents) {
+            this.checkInComponents.initialize()
+        }
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/my-books/MyBooksDropper.js:95]: This might be a good place for the JS optional chaining operator:
```suggestion
        this.checkInComponents?.initialize()
```

**Review by cdrini — APPROVED** [review]
Tested on https://testing.openlibrary.org/authors/OL15003393A/Dayeon_Auh and works like a charm!
