### PR TITLE
fix: accessibility for closing hamburger menu with keyboard 

### LINKED ISSUE #7917: User icon hamburger menu cannot be easily closed with keyboard.
It is not intuitive to close the user icon hamburger menu when navigating it with the keyboard. It should close when the focus is out of the menu and also when pressing the Esc key.

### Evidence / Screenshot (if possible)
The keyboard focus is now on the user icon hamburger menu.
Screen Shot 2023-05-31 at 5 10 03 PM

Click the space key, then you can go inside the menu.
Screen Shot 2023-05-31 at 5 10 19 PM

But you cannot easily close this menu. After pressing the tab key many times, the focus goes out from the menu. But the menu keeps visible.

### Relevant url?

https://openlibrary.org/

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Use the tab key and go to the user icon hamburger menu, and click the space key to go inside the menu.

* Actual: The menu keeps visible even after the keyboard focus moves out from the menu.
* Expected: When users are inside the menu, they should be able to escape from the menu by Esc key. Also, it should automatically close when the keyboard focus moves out from the menu.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 113.0.5672.126 (Official Build) (arm64)
- **Operating system?** macOS Monterey Version 12.3.1
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Keyboard navigation of the [Microfost Accessibility page](https://www.microsoft.com/en-us/accessibility) might be a good reference.

### PR DESCRIPTION
**Pull request by TanyaPina**
Closes #7917 

Issue: The user hamburger menu being unable to be closed through keyboard use, resulting in a menu that remains open even when focus is outside of it. 

This PR fixes this issue by enabling the user to exit header dropdown menus with the press of the Escape key. Additionally, it traps focus in the hamburger menu list by cycling through the list items until the user chooses to exit the menu with the escape key.

### Technical
While this PR applies escape key functionality to header dropdown menus, it currently fixes the focus issue within the hamburger dropdown menu specifically. A limitation with this fix would be if the user is in the last menu item and shift+tabs to go backwards, which results in them going to the first menu list item instead of the penultimate. 

### Testing
1. Tab to the user hamburger menu button on the far right side of the header
2. Press the "Enter" or "Space" key to open the dropdown menu
3. Tabbing all the way to the last list and then tabbing once more should bring the focus back to the first item of the list
4.  Pressing the "Escape" key will exit the menu and bring the focus to the next item.

### Screenshot
Loom video to show keyboard behavior:
https://www.loom.com/share/9f35dffdc8dd435f82a991f5be22db2a?sid=2cece70d-9271-494a-b81c-40822c6d5b85

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/index.js [hunk 1]
```diff
@@ -443,6 +443,16 @@ jQuery(function () {
...
 
+    $('.header-dropdown').on('keydown', function (event) {
+        if (event.key === 'Escape') {
+            $('details[open]').not(this).removeAttr('open');
+        }
+    });
+
+    $('.hamburger-dropdown-menu a').last().on('focusout', function () {
+        $('.hamburger-dropdown-menu a').first().trigger('focus');
+    });
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/index.js:454]: Stealing from our neighbours at Wikipedia, it seems like the pattern they use is that tabbing through the hamburger menu, when you get to the end, it _exits_. Something like when you `focusout` of the `.hamburger-dropdown-menu`, then close the menu. That seems to be a more standard interaction.

Comment (cdrini) [reply openlibrary/plugins/openlibrary/js/index.js:454]: Can we also make the other menus behave this way? E.g. the browse menu?

**Review by cdrini — CHANGES_REQUESTED** [review]
Nice, thank you @TanyaPina ! One UX/Accessibility change to the approach for focus out :+1:

**Comment by mekarpeles** [comment]
@TanyaPina, courtesy ping 😊  let us know when you have time to revisit

**Comment by cdrini** [comment]
Hey @TanyaPina ! Are you still working on this one? Anything we can do to help knock it over the finish line?

File: openlibrary/plugins/openlibrary/js/index.js (hunk 1 above)
Comment (TanyaPina) [reply openlibrary/plugins/openlibrary/js/index.js]: Hello Drini, I have updated my code to address both of these comments! All dropdown menus now exit when the user tabs through the end of the menu.

File: openlibrary/plugins/openlibrary/js/index.js [hunk 2]
```diff
@@ -443,6 +443,18 @@ jQuery(function () {
         $('details[open]').not(this).removeAttr('open');
     });
 
+    $('.header-dropdown').on('keydown', function (event) {
+        if (event.key === 'Escape') {
+            $('details[open]').not(this).removeAttr('open');
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/index.js:448]: `<details>` elements are used for a few miscellaneous things throughout the site; we don't need them all to close just the header ones.

```suggestion
            $('.header-dropdown > details[open]').not(this).removeAttr('open');
```

File: openlibrary/plugins/openlibrary/js/index.js [hunk 3]
```diff
@@ -443,6 +443,18 @@ jQuery(function () {
...
+        }
+    });
+
+    $('.dropdown-menu').each(function() {
+        $(this).find('a').last().on('focusout', function() {
+            $('details[open]').not(this).removeAttr('open');
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/index.js:454]: Ditto here

```suggestion
            $('.header-dropdown > details[open]').not(this).removeAttr('open');
```

**Review by cdrini — APPROVED** [review]
Lgtm! Tested both on desktop/mobile and works like a charm! One small fix.

File: openlibrary/plugins/openlibrary/js/index.js [hunk 4]
```diff
@@ -443,6 +443,18 @@ jQuery(function () {
...
+        if (event.key === 'Escape') {
+            $('.header-dropdown > details[open]').not(this).removeAttr('open');
+        }
+    });
+
+    $('.dropdown-menu').each(function() {
+        $(this).find('a').last().on('focusout', function() {
+            $('.header-dropdown > details[open]').not(this).removeAttr('open');
+        });
+    });
```
Comment (cdrini) [inline openlibrary/plugins/openlibrary/js/index.js:456]: Oh I see the one's above do this 😅 We also shouldn't be using `.not(this)` here, since we actually _do_ want to close `this`!
