### PR TITLE
original fix should have targeted submit, not click

### LINKED ISSUE #934: Save button should be disabled on click
I accidentally clicked the Save button a second time and created two identical edits here:

https://openlibrary.org/books/OL9286034M/A_First_Course_in_Database_Systems_(2nd_Edition)?m=history

The Save button should be disabled as soon as it's clicked and the update is submitted.

### PR DESCRIPTION
**Pull request by mekarpeles**
Closes #934 
re: #954 

Cc: @Num170R 

## Description:
Hotfix to previous commit; should have targeted action `submit` instead of `click` (which seems to have been catching the click and preventing the submit

### CODE REVIEW

File: openlibrary/plugins/openlibrary/js/automatic.js [hunk 1]
```diff
@@ -38,7 +38,7 @@ jQuery(function($) {
     $(".no-img img").hide();
 
     // disable save button after click
```
Comment (LeadSongDog) [inline openlibrary/plugins/openlibrary/js/automatic.js]: comment should now read "after submit" rather than "after click"
