### PR TITLE
Add load balancing to new solr to fix new solr getting overwhelmed by prod traffic

### LINKED ISSUE #3435: New Solr unable to handle production traffic
The new solr instance on ol-solr0 seems to be able to handle the traffic from one web node ok (although there is an increase in internal errors), but collapses when connected to both web nodes.

### Steps to Reproduce
1. Update ol-web3 and ol-web4 to use ol-solr0 instead of ol-solr2

* Actual: Big spike in internal errors, search generally results in `None` errors
* Expected: Everything ok

### Stakeholders
@mekarpeles

### PR DESCRIPTION
**Pull request by cdrini**
Closes #3435 ; Fix

### Technical
- Copied haproxy.cfg from prod's ol-solr2

### Testing
On local dev:
1. Comment out the memory mods in solr/start.sh (ain't got that much RAM!)
2. `docker-compose build solr`
3. `ENV=prod docker-compose up --no-deps -d solr`
    - [x] http://localhost:8983/solr/admin/ loads
    - [x] http://localhost:8983/admin?stats shows haproxy stats
4. `docker-compose down`
5. `docker-compose up --no-deps -d solr`
    - [x] http://localhost:8983/solr/admin/ loads
    - [x] http://localhost:8983/admin?stats does not load (blank screen)
6. `docker-compose down; docker-compose up -d`
    - [x] Searching work on local openlibrary

On on ol-solr0:
1. ~`docker-compose build solr`~ `sudo docker build --network=host -t olsolr:latest -f docker/Dockerfile.olsolr .`
2. `ENV=prod docker-compose up --no-deps -d solr`
    - [x] http://localhost:8983/solr/admin/ loads (was a little slow, but eventually came up!)
    - [x] http://localhost:8983/admin?stats shows haproxy stats

### Stakeholders
@mekarpeles

### CODE REVIEW

**Comment by cdrini** [comment]
Ok, it now handles prod traffic after the optimize. We might not need haproxy at all, but would rather not deal with testing that. Not also haven't tested the modified Jenkinsfile.

File: conf/solr/start.sh [hunk 1]
```diff
@@ -0,0 +1,20 @@
+#!/bin/bash
+
+# Default to dev env
+ENV=${ENV:-dev}
+
+ln -sf /etc/solr/conf/solrconfig-$ENV.xml /etc/solr/conf/solrconfig.xml
+
+# On dev, don't use haproxy; make tomcat serve directly to 8983
+if [ "$ENV" = "dev" ] ; then
+    sed -i 's/8080/8983/g' /var/lib/tomcat7/conf/server.xml;
```
Comment (mekarpeles) [inline conf/solr/start.sh:10]: this could bite us eventually? no way of knowing (while within server.xml) not to add values 8080 or 8983 :P

File: conf/solr/start.sh [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+fi
+
+if [ "$ENV" = "prod" ] ; then
```
Comment (mekarpeles) [inline conf/solr/start.sh:13]: note: only assumes 10gb ram if on prod
